### ISSUE TITLE
Fails with errors

### ISSUE THREAD

**Issue by littke** [xorcery/coyote#7]
$ coyote styles.less:styles.css
- styles.less
  /var/lib/gems/1.8/gems/coyote-1.1.0/lib/coyote.rb:32:in `round': wrong number of arguments (1 for 0) (ArgumentError)
  from /var/lib/gems/1.8/gems/coyote-1.1.0/lib/coyote.rb:32:in`build'
  from /var/lib/gems/1.8/gems/coyote-1.1.0/lib/coyote.rb:16:in `run'
  from /var/lib/gems/1.8/gems/coyote-1.1.0/lib/coyote/cli.rb:18
  from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
  from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
  from /var/lib/gems/1.8/gems/coyote-1.1.0/bin/coyote:5
  from /var/lib/gems/1.8/bin/coyote:19:in`load'
  from /var/lib/gems/1.8/bin/coyote:19

**Comment by BruceClark** [comment]
$ coyote -w styles.less:styles.css 

You didn't give Coyote a command for what to do. I always recommend checking the page help or examples. 

We should improve error handling though. Hope this helps.

**Comment by littke** [comment]
I tried that too!

```
$ coyote -w styles.less:styles.css

/var/lib/gems/1.8/gems/coyote-1.1.0/lib/coyote/cli.rb:16: private method `split' called for nil:NilClass (NoMethodError)
  from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
  from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
  from /var/lib/gems/1.8/gems/coyote-1.1.0/bin/coyote:5
  from /var/lib/gems/1.8/bin/coyote:19:in `load'
  from /var/lib/gems/1.8/bin/coyote:19
```

**Comment by BruceClark** [comment]
Less compiling is dependent on installation of lessc, do you have that installed?

**Comment by caseyohara** [comment]
@littke what version of Ruby are you running?

**Comment by littke** [comment]
```
$ gem list | grep less
less (2.2.1)

$ ruby -v
ruby 1.8.7 (2010-08-16 patchlevel 302) [x86_64-linux]
```

**Comment by caseyohara** [comment]
@littke It looks like an issue with Ruby 1.8.7. We're working on supporting older versions of Ruby. Thanks for the issue.

**Comment by littke** [comment]
Thanks.

I took for granted my version of Ruby was the latest one. Not a Ruby hacker, here. Might want to add a 'Dependencies' section in the README that includes version numbers. Thanks guys.

**Comment by littke** [comment]
It seems 1.8 is the latest version I'm able to run in Debian stable. Ruby 1.9.1 is available, but rubygems1.9 isn't. 

I tried this:

`$ /usr/bin/ruby1.9.1 /var/lib/gems/1.8/gems/coyote-1.1.0/bin/coyote`

but that failed:

`<internal:lib/rubygems/custom_require>:29:in`require': no such file to load -- term/ansicolor (LoadError)`

Is there anything I can do? I don't know my way around here. Thanks. Really appreciate it.

**Comment by littke** [comment]
(same thing happened with `-w file.less:file.css`.)

**Comment by littke** [comment]
hello?

**Comment by brycehammond** [comment]
@littke I'd recommend trying rbenv (https://github.com/sstephenson/rbenv) to get local copies of Ruby 1.9.2 and the corresponding gemset.  Either way, you'll need to do a 'gem install coyote' in whatever ruby you are using.  Trying to execute ruby gems in gemsets from other rubys isn't going to work nicely.

**Comment by littke** [comment]
Thanks.

On 29 maj 2012, at 16:45, Bryce Hammond
reply@reply.github.com
wrote:
